{% set version = "0.9.0" %}

package:
  name: qjson
  version: {{ version }}

source:
  url: https://github.com/flavio/qjson/archive/{{ version }}.tar.gz
  sha256: e812617477f3c2bb990561767a4cd8b1d3803a52018d4878da302529552610d4
  patches:
    - enable_language.patch  # [osx]

build:
  skip: True  # [win and vc<14]
  number: 1007

requirements:
  build:
    - cmake
    - make  # [linux]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - qt-main
  run:
    - qt-main

test:
  commands:
    - test -f ${PREFIX}/lib/libqjson-qt5${SHLIB_EXT}  # [not win]
    - if not exist %LIBRARY_BIN%\\qjson-qt5.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\qjson-qt5.lib exit 1  # [win]

about:
  home: https://github.com/flavio/qjsonhttp://qjson.sourceforge.net/
  license: LGPL-2.1-only
  license_file: README.license
  summary: 'QJson is a qt-based library that maps JSON data to QVariant objects'
  description: |
      JSON (JavaScript Object Notation) is a lightweight data-interchange format.
      It can represents integer, real number, string, an ordered sequence of value,
      and a collection of name/value pairs.
      QJson is a Qt-based library that maps JSON data to QVariant objects and vice versa.
  doc_url: http://qjson.sourceforge.net/usage/
  dev_url: https://github.com/flavio/qjson

extra:
  recipe-maintainers:
    - ceholden
