appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: hZfatvcpDPw/2/1UBwbxXPrkye55ET3PXopIfCp8aL+Nh0BgNoEPxxLi9YYOMnlHYE/v64t6IzQb+eKDfTlPCDXzp1rZgO2RimFebA+cxFjce0ywcx7uzNXfbfvyDNEofv61qqfy7ngLKeSXfG3+jRq5SGwmZgldAFKoE7vYNOEu/nEPQ1dpTsEOl0I3fYTvUrFPn96wVQE4ZUZ3Bnujqqu6vLhgHUVKZQ4kET8H2bdlwQV1t1rmklS10CaQVhgcGStH37VLmf9LYWcK9PRItdjXqM5wXGorcXTHEnwl7NfVuJlMXbFu7T0RID+ok2Ab90FHnpnSm4cb0hw3Jt+Y+phhpNIKrzBpMsgjc2osjXLAWEowuZcL7lqK0vt1U0JMYUv2Cbx/DieaVF9x7rbb5jjFHxC6g+yMYL6710hILOD6B9fALYidm/mba0xpCIImQ0vNYz8gkBCMq3DG353kiQsJB3zsip4kkis+ENNVxHfDADF+ILBmQGWHf1dUjvvnO/da1lOpBxDlYL32B8rdSrDuIa/2tx3yi4LKxjXObiXdsqq+sC3D6zVEoU2p2jX+kh/1r46zc5H/JGSVWly9TBM79meOQZEUYAmAI8SKZwTQ8NrjwkTzug+et6xPDRGWwTVH4bdlKUDN7hsCrJIbp0Ze0cDERk1/SqI5e2bGCi0=}
provider:
  win: azure
